ZO1.Tutorials.WebUI/Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using ZO1.Tutorials.Services.Services.Interface;
using ZO1.Tutorials.Services.ViewModels.Expenses;

namespace ZO1.Tutorials.WebUI.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly IExpenseService _expenseService;
        private readonly IExpenseTypeService _expenseTypeService;

        public ExpenseController(IExpenseService expenseService
            , IExpenseTypeService expenseTypeService)
        {
            _expenseTypeService = expenseTypeService;
            _expenseService = expenseService;
        }

        // GET
        public IActionResult Index()
        {
            var expenses = _expenseService.GetExpensesWithExpenseType().ToList();
            return View(expenses);
        }

        public IActionResult Create()
        {
            var createExpenseTypesVm = new CreateExpenseViewModels
            {
                ExpenseTypesDropDown = _expenseTypeService.GetAllExpenseTypesDropDown()
            };

            return View(createExpenseTypesVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateExpenseViewModels model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = _expenseService.CreateExpense(model.CreateExpenseViewModel);
            if (result.IsSuccess)
            {
                TempData["SuccessMess"] = $"Add Expense '{model.CreateExpenseViewModel.ExpenseName}' Success";
                return RedirectToAction("Index");
            }

            TempData["FailMess"] = $"Add Expense '{model.CreateExpenseViewModel.ExpenseName}' Fail";
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var expense = _expenseService.GetExpenseById(id);
            if (expense != null)
            {
                var createExpenseTypesVm = new CreateExpenseViewModels
                {
                    CreateExpenseViewModel = expense,
                    ExpenseTypesDropDown = _expenseTypeService.GetAllExpenseTypesDropDown()
                };
                return View(createExpenseTypesVm);
            }

            TempData["FailMess"] = "Can't found any Expense match with";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(CreateExpenseViewModels model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = _expenseService.UpdateExpense(model.CreateExpenseViewModel);
            if (result != null)
            {
                TempData["SuccessMess"] = $"Update Expense '{model.CreateExpenseViewModel.ExpenseName}' Success";
                return RedirectToAction("Index");
            }

            TempData["FailMess"] = $"Update Expense '{model.CreateExpenseViewModel.ExpenseName}' Fail";
            return RedirectToAction("Index");
        }



        public IActionResult Delete(int id)
        {
            var result = _expenseService.DeleteExpense(id);

            if (result.IsSuccess)
            {
                TempData["SuccessMess"] = "Delete Expense Success";
                return RedirectToAction("Index");
            }
            TempData["FailMess"] = "Delete Expense Fail";
            return RedirectToAction("Index");
        }
    }
}

ZO1.Tutorials.WebUI/Controllers/ExpenseTypeController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using ZO1.Tutorials.Services.Services.Interface;
using ZO1.Tutorials.Services.ViewModels.ExpenseTypes;

namespace ZO1.Tutorials.WebUI.Controllers
{
    public class ExpenseTypeController : Controller
    {
        private readonly IExpenseTypeService _expenseTypeService;

        public ExpenseTypeController(IExpenseTypeService expenseTypeService)
        {
            _expenseTypeService = expenseTypeService;
        }

        // GET
        public IActionResult Index()
        {
            var expenseTypes = _expenseTypeService.GetAllExpenseTypes().ToList();
            return View(expenseTypes);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateExpenseTypeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var result = _expenseTypeService.CreateExpenseType(model);
            if (result.IsSuccess)
            {
                TempData["SuccessMess"] = $"Add ExpenseType '{model.Name}' success";
                return RedirectToAction("Index");
            }

            TempData["FailMess"] = $"Add ExpenseType '{model.Name}' fail";
            return RedirectToAction("Index");
        }


        public IActionResult Update(int id)
        {
            var expenseTypes = _expenseTypeService.GetExpenseTypeById(id);
            return View(expenseTypes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(CreateExpenseTypeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var result = _expenseTypeService.UpdateExpenseType(model);
            if (result.IsSuccess)
            {
                TempData["SuccessMess"] = $"Update ExpenseType '{model.Name}' success";
                return RedirectToAction("Index");
            }

            TempData["FailMess"] = $"Update ExpenseType '{model.Name}' fail";
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var result = _expenseTypeService.DeleteExpenseType(id);
            if (result.IsSuccess)
            {
                TempData["SuccessMess"] = "Delete ExpenseType success";
                return RedirectToAction("Index");
            }

            TempData["FailMess"] = "Delete ExpenseType fail";
            return RedirectToAction("Index");
        }

    }
}

ZO1.Tutorials.WebUI/Controllers/ItemController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using ZO1.Tutorials.Services.Services.Interface;
using ZO1.Tutorials.Services.ViewModels.Items;

namespace ZO1.Tutorials.WebUI.Controllers
{
    public class ItemController : Controller
    {
        // GET
        private readonly IItemService _itemService;

        public ItemController(IItemService itemService)
        {
            _itemService = itemService;
        }

        public IActionResult Index()
        {
            var items = _itemService.GetAllItem().ToList();

            return View(items);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateItemViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var result = _itemService.CreateItem(model);
            if (result.IsSuccess)
            {
                TempData["SuccessMess"] = $"Add Item '{model.ItemName}' Success";
                return RedirectToAction("Index");
            }

            TempData["FailMess"] = $"Add Item '{model.ItemName}' Fail";
            return RedirectToAction("Index");
        }
    }
}

ZO1.Tutorials.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BorrowedWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
    <style>
        .field-validation-error { 
            color: red
        }
        .validation-summary-errors {
            color: red
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Uta95s</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Borrowed</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">Expense</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExpenseType" asp-action="Index">Expense Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ZO1.Tutorials.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>